export const FETCH_NEWS_START = 'FETCH_NEWS_START';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAIL = 'FETCH_NEWS_FAIL';
export const ADD_NEWS_SUCCESS = 'ADD_NEWS_SUCCESS';
export const ADD_NEWS_FAIL = 'ADD_NEWS_FAIL';
export const EDIT_NEWS_SUCCESS = 'EDIT_NEWS_SUCCESS';
export const EDIT_NEWS_FAIL = 'EDIT_NEWS_FAIL';
export const DELETE_NEWS_SUCCESS = 'DELETE_NEWS_SUCCESS';
export const DELETE_NEWS_FAIL = 'DELETE_NEWS_FAIL';
export const RESET_IS_DONE = 'RESET_IS_DONE';

export const FETCH_MATCHES_START = 'FETCH_MATCHES_START';
export const FETCH_MATCHES_SUCCESS = 'FETCH_MATCHES_SUCCESS';
export const FETCH_MATCHES_FAIL = 'FETCH_MATCHES_FAIL';
export const ADD_MATCH_SUCCESS = 'ADD_MATCH_SUCCESS';
export const ADD_MATCH_FAIL = 'ADD_MATCH_FAIL';
export const EDIT_MATCH_SUCCESS = 'EDIT_MATCH_SUCCESS';
export const EDIT_MATCH_FAIL = 'EDIT_MATCH_FAIL';
export const DELETE_MATCH_SUCCESS = 'DELETE_MATCH_SUCCESS';
export const DELETE_MATCH_FAIL = 'DELETE_MATCH_FAIL';

export const FETCH_HOUSES_START = 'FETCH_HOUSES_START';
export const FETCH_HOUSES_SUCCESS = 'FETCH_HOUSES_SUCCESS';
export const FETCH_HOUSES_FAIL = 'FETCH_HOUSES_FAIL';

export const FETCH_TEACHERS_START = 'FETCH_TEACHERS_START';
export const FETCH_TEACHERS_SUCCESS = 'FETCH_TEACHERS_SUCCESS';
export const FETCH_TEACHERS_FAIL = 'FETCH_TEACHERS_FAIL';
export const ADD_TEACHER_SUCCESS = 'ADD_TEACHER_SUCCESS';
export const ADD_TEACHER_FAIL = 'ADD_TEACHER_FAIL';
export const EDIT_TEACHER_SUCCESS = 'EDIT_TEACHER_SUCCESS';
export const EDIT_TEACHER_FAIL = 'EDIT_TEACHER_FAIL';
export const DELETE_TEACHER_SUCCESS = 'DELETE_TEACHER_SUCCESS';
export const DELETE_TEACHER_FAIL = 'DELETE_TEACHER_FAIL';
